# for dev/master branch
-
  version: 2.0.0-rc1-{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
    - master
    - feature/dnx
  skip_tags: true
  image: Visual Studio 2015
  configuration: Debug
  platform: Any CPU
  install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-update1
  before_build:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  build:
    verbosity: quiet
  test_script:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  - ps: ./run-tests.ps1

# for release/all branch
-
  version: 2.0.0-rc1-{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release/all
  skip_tags: true
  image: Visual Studio 2015
  configuration: Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    project_name: Aluencube.EntityContextLibrary
    github_auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
  install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-update1
  before_build:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  - ps: ./run-project-versioning.ps1
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: quiet
  test_script:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  - ps: ./run-tests.ps1
  artifacts:
  - path: artifacts\bin\$(project_name)\$(configuration)\*.nupkg
    name: EntityContextLibrary
  deploy:
  - provider: NuGet
    api_key:
      secure: ZdI7BA2YRQg/yRMPbRGTTJeGWj3X3o8kNhf4LeA5YkV072GpmKwQ3aW+KVgMbkZX
    artifact: EntityContextLibrary
    on:
      branch: release/all
      platform: Any CPU
      configuration: Release
  after_deploy:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - cmd: git push origin --delete release/all
