# for dev/master branch
-
  version: 2.0.0-alpha-{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
    - master
  skip_tags: true
  image: Visual Studio 2015
  configuration: Debug
  platform: Any CPU
  install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-update1
  build_script:
  - ps: ./build-solution.ps1 -Config $env:configuration
  test_script:
  - ps: ./run-tests.ps1

# for release/all branch
-
  version: 2.0.0-alpha-{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release/all
  skip_tags: true
  image: Visual Studio 2015
  configuration: Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    project_name: Aliencube.EntityContextLibrary
    github_auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
  install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-update1
  nuget:
    account_feed: true
    disable_publish_on_pr: true
  build_script:
  - ps: ./run-project-versioning.ps1 -Project $env:project_name
  - ps: ./build-solution.ps1 -Config $env:configuration
  test_script:
  - ps: ./run-tests.ps1
  - ps: ./publish-package.ps1 -Config $env:configuration -Project $env:project_name
  artifacts:
  - path: artifacts\bin\$(project_name)\$(configuration)\*.nupkg
    name: Aliencube.EntityContextLibrary
  deploy:
  - provider: NuGet
    api_key:
      secure: ZdI7BA2YRQg/yRMPbRGTTJeGWj3X3o8kNhf4LeA5YkV072GpmKwQ3aW+KVgMbkZX
    artifact: Aliencube.EntityContextLibrary
    on:
      branch: release/all
      platform: Any CPU
      configuration: Release
  - provider: GitHub
    tag: v$(appveyor_build_version)
    description: $(project_name)-v$(appveyor_build_version) has been released
    auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
    artifact: Aliencube.EntityContextLibrary
    on:
      branch: release/all
      platform: Any CPU
      configuration: Release
  after_deploy:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - cmd: git push origin --delete release/all
